Scope the ~dev fallback to the version missing from stable
It looks like that when a package version is not found on Packagist (here StimulusBundle 2.8), then the process fails for all other version of the package.

**Before:**
```
Error: Version "2.13" of "symfony/stimulus-bundle" does not exist on Packagist
Error: Version "2.20" of "symfony/stimulus-bundle" does not exist on Packagist
Error: Version "2.24" of "symfony/stimulus-bundle" does not exist on Packagist
Error: Version "2.25" of "symfony/stimulus-bundle" does not exist on Packagist
Error: Version "2.8" of "symfony/stimulus-bundle" does not exist on Packagist
Error: Version "2.9" of "symfony/stimulus-bundle" does not exist on Packagist
```

**After:**
```
Error: Version "2.8" of "symfony/stimulus-bundle" does not exist on Packagist
```